### ISSUE TITLE
Can't play C+1

### ISSUE THREAD

**Issue by windlight2** [isalin/TBbard#11]
The program won't play the highest note in-game C+1. Even with a simple midi containing all 37 notes at octave 3, once it reaches the final note it just scales it down to C instead of sending an {8} keystroke for C+1.

[key_test.zip](https://github.com/isalin/TBbard/files/2108143/key_test.zip)

**Comment by isalin** [comment]
Ah, that's because they renamed it from “C+2” to “C+1” in the new perform system (it used to look like this https://i.imgur.com/P1PurNL.png). 

The third octave used to be called “X+1”. So C+2 should send 8.

There was also a latency issue with C+2 in the original perform system, so I decided to convert all C+2 into C+1 when parsing midi files. But that shouldn’t be an issue anymore with the current perform system. I’ll look into fixing that! It’ll probably still be called C+2 though.

**Comment by windlight2** [comment]
Thanks for fixing this!
