### ISSUE TITLE
Min FPS in 4.31

### ISSUE THREAD

**Issue by windlight2** [isalin/TBbard#12]
Is there any reason for the min FPS/delay setting to be there after patch 4.31 seeing as in-game input lag has been fixed? I find that leaving it at the default value of 59 results in a lot of my songs, faster ones in particular, sounding very choppy. I've worked around this by setting the min FPS value to 1000 which results in a delay=1. Maybe getting rid of any artificial input delay will help notes play for their true duration.

On a related note, is there any way to make TBbard respect the true timings of notes and rests (including rest notes at the beginning of the midi which are currently ignored) so that it would be possible to keep different tracks from the same midi in sync for composition purposes?

**Comment by isalin** [comment]
The lag was mostly fixed with the new perform system. Unfortunately, input in ffxiv is only processed every frame. 

For an example, if we have a solid 60 fps, every frame is ~16.6 ms. If we then have fast paced songs with faster than 16.6 ms inputs, ffxiv will just start ignoring stuff (this also affects combat!). Even with the new perform system. 

It’s mostly an issue when not using the full keyboard layout, as both pressing and letting go of ctrl/shift requires a frame to process. 

Hmm. You are correct that there is some further delay that could be removed when using the full layout though. It actually seems like I might’ve missed to edit a bit of code that should’ve cut out a lot of delay when using the full keyboard layout in the new perform system… 

Here’s an untested version that should cut out a lot of that delay if you want to try it out!

[TBbard_v1.8b.zip](https://github.com/isalin/TBbard/files/2108549/TBbard_v1.8b.zip)

I didn’t consider that the delay at the start could be used to sync stuff up for composition! That actually sounds amazing! 

It's getting a bit late here now, but I’ll add a checkbox to keep the delays at the start sometime tomorrow.

**Comment by windlight2** [comment]
Thanks! But I noticed that the app is having trouble with releasing held notes when the same note is played consecutively.

**Comment by isalin** [comment]
I pretty much just disabled the fps based delays in that version. 

What happens is that the game sees the button held down, TBbard lets go and presses the note again, but that happens faster than a frame in ffxiv. And since the game only processes input on a frame, it just ends up thinking that the key was held down the whole time. 

I’ll try to make it look ahead to check if it’s going to play the same note next time and have it let go early.

**Comment by isalin** [comment]
Sorry that it took a little longer than expected, life got busy for a while there. I've implemented a fix for the held note issue and an option to use the true timings for everything for compositions (make sure you use your real fps!).

**Comment by windlight2** [comment]
Thank you so much! I'll give it a try tonight.
