### ISSUE TITLE
Instrument selector behaves strangely

### ISSUE THREAD

**Issue by DanaGoyette** [isalin/TBbard#14]
For basically every MIDI file I've ever tried loading, the instrument selection dropdown shows nonsense, either lumping multiple instruments together, or a showing a bunch of empty lines, or both.

One particularly amusing example: MARS.MID file from the old game, Outpost 1.5.
The emulator package here has it: https://www.outpost2.net/outpost1.html

The "instrument" dropdown shows the supposed instrument 14 as follows:
`14. Bassoon, Bassoon, Trumpet, Contrabass, Trumpet, Bassoon, Trumpet, Oboe, Trumpet, Trombone, Contrabass, Trumpet, Contrabass, Trumpet, Trumpet, Trumpet, Trumpet, Contrabass, Trumpet`

**Comment by isalin** [comment]
Yeah, I’ve noticed the same. It’s mostly because of how MIDI files are structured.

They have a fixed number of channels. Each is supposed to correspond to a different instrument so that multiple instruments can be played at once etc.

Unfortunately, it seems like it’s very common for people to just switch out the instrument of the channel mid-song instead of using another channel.

So, the reason why you might get “Bassoon, Bassoon, Trumpet…” is because they started encoding the channel 14 with a bassoon, then at some point they changed to a 2nd type of bassoon, and then later to a trumpet. 

Design wise, it was a choice between either not showing all the instruments encoded on that channel, or showing several instruments that might look a bit messy.

I suppose I should make sure to at least filter out duplicate instruments and hide the empty unused channels.

I probably won’t have time to look into it until the weekend though.

**Comment by isalin** [comment]
I've added filtering for unused instrument channels (no more "blank" instruments!) and duplicate instrument names.

Sorry it took a bit longer than promised!
