### ISSUE TITLE
Some MIDI files come up completely empty

### ISSUE THREAD

**Issue by DanaGoyette** [isalin/TBbard#18]
Among my random collection of midi files, there are a bunch that used to come up with blank track titles (see #14), but with the latest change, they now show up completely empty.  There are also some midi files that have always appeared completely empty.

Here's one such file:
http://www.pianoeducation.org/babakiev.mid

**Comment by isalin** [comment]
Hi!

I see what the issue is. When a midi file doesn't specify an instrument at all, the convention appears to be to just default to "Piano". I didn't consider that midi files could just skip specifying an instrument, and so when I added the thing that filtered out "blank instruments/channels", those ended up being removed as well.

I've attempted to implement a fix here:
[1.12.zip](https://github.com/isalin/TBbard/files/2705501/1.12.zip)

I would be great if you could test one or two of the other files that showed up empty and verify that the fix works!

**Comment by isalin** [comment]
Wonderful!

And good point. I've changed it so that it's now listed as "Unspecified" in the drop down instead, and uploaded the new version in the releases page.

Thank you for reporting the bug and helping out!
