### ISSUE TITLE
w0 issue when open some midi files

### ISSUE THREAD

**Issue by hyskylord** [isalin/TBbard#4]
I tested some MIDI files, and it seems quite a few of them didn't give the right interval between notes where all of the wait command was "w0" instead of the correct number

**Comment by isalin** [comment]
I don't suppose you could link me an example file?

**Comment by m19025** [comment]
[mid.zip](https://github.com/isalin/TBbard/files/1780628/mid.zip)

**Comment by isalin** [comment]
Ah, I see. I appear to have made a rounding error for files with a very high tick rate. There was a long in a place where there should've been a float! 

Would you mind double checking that this version works?

Also, the file you linked might not sound exactly like you'd hope since ffxiv can't play those kinds of drawn out notes. Luckily there's a huge amount of HP midi files floating around!

[TBbard_v1.6.zip](https://github.com/isalin/TBbard/files/1780833/TBbard_v1.6.zip)

**Comment by hyskylord** [comment]
Thank you! Now it works pretty well for those files.
