### ISSUE TITLE
Version 1.7 play button not working.

### ISSUE THREAD

**Issue by Supagetti** [isalin/TBbard#8]
I've run the application as administrator, and I've even tried compatibility for windows 8. But still for some reason or another clicking play won't start the timer, and nothing seems to happen. Version 1.6 still works perfectly however. Any insight at all? 
Love the application by the way, thanks for all the work you've put into it.

**Comment by isalin** [comment]
Oh, I see. It turns out it's related to the save/load system. If there was no previously saved data, the "Wait Multipler" would default to an integer 1 and it should've been a double.  

It saves and loads as a double, and since it always saved and loaded automatically for me during testing, I never noticed that the default value was wrong. Thank you for reporting it!

I've pushed an updated version that should fix it.

**Comment by Supagetti** [comment]
1.7a works perfectly! 

Thanks!
